import Vue from 'vue';
import {
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Tooltip,
  Drawer,
  Table,
  TableColumn,
  Notification,
  Badge,
  Row,
  Avatar,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Aside,
  Container,
  Col,
  Card,
  Main,
  Carousel,
  CarouselItem,
  Header,
  Tabs,
  TabPane,
  Tree,
  Steps,
  Step,
  MessageBox,
  Dialog
} from 'element-ui';
Vue.use(Dialog);
Vue.prototype.$alert = MessageBox;
Vue.use(Step);
Vue.use(Steps);
Vue.use(Tree);
Vue.use(TabPane);
Vue.use(Tabs);
Vue.use(Header);
Vue.use(CarouselItem);
Vue.use(Carousel);
Vue.use(Main);
Vue.use(Card);
Vue.use(Col);
Vue.use(Container);
Vue.use(Aside);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Dropdown);
Vue.use(Row);
Vue.use(Avatar);
Vue.use(Badge);
Vue.prototype.$notify = Notification;
Vue.use(TableColumn);
Vue.use(Table);
Vue.use(Drawer);
Vue.use(Tooltip);
Vue.use(Submenu);
Vue.use(MenuItemGroup);
Vue.use(MenuItem);
Vue.use(Menu);
Vue.prototype.$message = Message;
Vue.use(Input);
Vue.use(FormItem);
Vue.use(Form);
Vue.use(Button);
